server:
  port: 8004
logging:
  level:
    org.zalando.logbook: DEBUG
spring:
  application:
    name: deal
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  liquibase:
    database-change-log-lock-table: DEAL_DATABASECHANGELOGLOCK
integration:
  conveyor:
    client:
      url: ${INTEGRATION_CONVEYOR_CLIENT_URL}
      connect-timeout: 30
      read-timeout: 30
      write-timeout: 30
  dossier:
    bootstrap-servers: ${INTEGRATION_DOSSIER_BOOTSTRAPSERVERS}
    topic:
      finish-registration: 'conveyor-finish-registration'
      create-document: 'conveyor-create-documents'
      send-document: 'conveyor-send-documents'
      send-ses: 'conveyor-send-ses'
      credit-issued: 'conveyor-credit-issued'
      application-denied: 'conveyor-application-denied'