server:
  port: 8006
logging:
  level:
    org.zalando.logbook: DEBUG
integration:
  deal:
    client:
      url: ${INTEGRATION_DEAL_CLIENT_URL}
      connect-timeout: 30
      read-timeout: 30
      write-timeout: 30

